### ISSUE TITLE
Add Packages Meta Information API

### ISSUE THREAD

**Issue by Kinflou** [ComlineProject/package-registry#1]
# The task
The package registry doesn't have the packages but should know how many are registered, if their file host service is working, and that kind of source information.

## What to do:
- [ ] Create a module in `src/web/api/` called `packages`
- [ ] Create a route point function called `register_routes` (like the other APIs in that directory do)
- [ ] Add a route for `/api/packages/info` and specify a getter for the function in the point below:
- [ ] Make a function called `packages_meta` and make it return a structure called `PackagesMeta` with the Default derive(#[derive(Default)]) and with the fields `total_count: usize`, `available_count: usize`, `hosts: HostMeta`(create this struct) and return a default
